default: &default
  #adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #username: root
  #password:
  #socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: kids_album25_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: kids_album25_test

production:
  <<: *default
  #database: kids_album25_production
  #username: kids_album25
  #password: <%= ENV['kids_album25_DATABASE_PASSWORD'] %>
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>